spring:
   datasource:
     username: heroscape
     password: heroscape
     url: jdbc:mysql://localhost:3306/heroscape
   
   jpa:
      hibernate:
         ddl-auto: none
      show-sql: true
      
   sql:
      init:
         mode: always
         